# SPDX-FileCopyrightText: 2023 Rivos Inc.
#
# SPDX-License-Identifier: Apache-2.0

name: linux-riscv-ci-patches

defaults:
  run:
    shell: bash -leo pipefail {0}

on: workflow_dispatch

jobs:
  build-patches:
    runs-on: arc-runner-set-2
    timeout-minutes: 50400 # 35 days
    container:
      image: ghcr.io/linux-riscv/pw-runner-multi:latest
    steps:
      - name: Configure git
        run: |
          git config --global --add safe.directory '*'
      - name: Checkout git
        run: |
          mkdir -p /build/my-linux
          cd /build/my-linux
          git init
          git remote add origin https://github.com/${{ github.repository }}
          git fetch origin ${{ github.event.pull_request.head.sha }}
          git reset --hard ${{ github.event.pull_request.head.sha }}
      - name: Run checks
        run: |
          cd /build/my-linux && bash .github/scripts/patches.sh
